// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZhDIiYlIEazqJHRmxzFzqD8nZOQcyoA',
    appId: '1:33357676892:android:462358ee1e03fe5d31c199',
    messagingSenderId: '33357676892',
    projectId: 'chatify-6c986',
    databaseURL: 'https://chatify-6c986-default-rtdb.firebaseio.com',
    storageBucket: 'chatify-6c986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb1xzd7rvhWRFDniYKrlSc3vvhUJFI1TY',
    appId: '1:33357676892:ios:3c33fa2e156a60a031c199',
    messagingSenderId: '33357676892',
    projectId: 'chatify-6c986',
    databaseURL: 'https://chatify-6c986-default-rtdb.firebaseio.com',
    storageBucket: 'chatify-6c986.appspot.com',
    iosClientId: '33357676892-jr68hce246j0u05l54livfoms95406e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatify',
  );
}
